package uk.ac.reading.sis05kol.engine.menuactivity.animations.elements;

import uk.ac.reading.sis05kol.engine.R;

public enum Element {

    STORMATTACK(new int[]{
            R.drawable.sa1,
            R.drawable.sa2,
            R.drawable.sa3,
            R.drawable.sa4,
            R.drawable.sa5,
            R.drawable.sa6,
            R.drawable.sa7,
            R.drawable.sa8,
            R.drawable.sa9
    },9,0),
    STORMIDLE(new int[]{
            R.drawable.si1,
            R.drawable.si1,
            R.drawable.si2,
            R.drawable.si3,
            R.drawable.si4,
            R.drawable.si5,
            R.drawable.si6,
            R.drawable.si7,
            R.drawable.si8,
            R.drawable.si9,
            R.drawable.si10,
            R.drawable.si11,
            R.drawable.si12,
            R.drawable.si13

    },13,3),

    FIREATTACK(new int[]{
            R.drawable.fa1,
            R.drawable.fa2,
            R.drawable.fa3,
            R.drawable.fa4,
            R.drawable.fa5,
            R.drawable.fa6,
            R.drawable.fa7,
            R.drawable.fa8,
            R.drawable.fa9},9,0),

    FIREIDLE(new int[]{
            R.drawable.fi1,
            R.drawable.fi2,
            R.drawable.fi3,
            R.drawable.fi4,
            R.drawable.fi5,
            R.drawable.fi6,
            R.drawable.fi7,
            R.drawable.fi8,
            R.drawable.fi9,
            R.drawable.fi10,
            R.drawable.fi11,
            R.drawable.fi12,
            R.drawable.fi13,
            R.drawable.fi14,
            R.drawable.fi15,
            R.drawable.fi16,
            R.drawable.fi17,
            R.drawable.fi18,
            R.drawable.fi19,
            R.drawable.fi20,
            R.drawable.fi21,
            R.drawable.fi22,
            R.drawable.fi23,
            R.drawable.fi24,
            R.drawable.fi25,
            R.drawable.fi26,
            R.drawable.fi27
    },27,0),

    ICEATTACK(new int[]{
            R.drawable.ia1,
            R.drawable.ia2,
            R.drawable.ia3,
            R.drawable.ia4,
            R.drawable.ia5,
            R.drawable.ia6,
            R.drawable.ia7,
            R.drawable.ia8,
            R.drawable.ia9},9,0),
    ICEIDLE(new int[]{
            R.drawable.ii1,
            R.drawable.ii2,
            R.drawable.ii3,
            R.drawable.ii4,
            R.drawable.ii5,
            R.drawable.ii6,
            R.drawable.ii7,
            R.drawable.ii8,
            R.drawable.ii9,
            R.drawable.ii10,
            R.drawable.ii11,
            R.drawable.ii12,
            R.drawable.ii13,
            R.drawable.ii14,
            R.drawable.ii15,
            R.drawable.ii16,
            R.drawable.ii17,
            R.drawable.ii18,
            R.drawable.ii19,
            R.drawable.ii20,
            R.drawable.ii21,
            R.drawable.ii22,
            R.drawable.ii23,
            R.drawable.ii24,
            R.drawable.ii25,
            R.drawable.ii26,
            R.drawable.ii27,
            R.drawable.ii28,
            R.drawable.ii29,
            R.drawable.ii30,
            R.drawable.ii31,
            R.drawable.ii32,
            R.drawable.ii33,
            R.drawable.ii34},34,0),


    POISONIDLE(new int[]{
        R.drawable.pa1,R.drawable.pa2,R.drawable.pa3,
                R.drawable.pa4,R.drawable.pa5,R.drawable.pa6,
                R.drawable.pa7,R.drawable.pa8,R.drawable.pa9},9,0),
    POISONATTACK(new int[]{
            R.drawable.pi1,
            R.drawable.pi2,
            R.drawable.pi3,
            R.drawable.pi4,
            R.drawable.pi5,
            R.drawable.pi6,
            R.drawable.pi7,
            R.drawable.pi8,
            R.drawable.pi9,
            R.drawable.pi10,
            R.drawable.pi11,
            R.drawable.pi12,
            R.drawable.pi13,
            R.drawable.pi14,
            R.drawable.pi15,
            R.drawable.pi16,
            R.drawable.pi17,
            R.drawable.pi18,
            R.drawable.pi19,
            R.drawable.pi20,
            R.drawable.pi21,
            R.drawable.pi22,
            R.drawable.pi23,
            R.drawable.pi24,
            R.drawable.pi25,
            R.drawable.pi26,
            R.drawable.pi27,
            R.drawable.pi28,
            R.drawable.pi29,
            R.drawable.pi30,
            R.drawable.pi31,
            R.drawable.pi32,
            R.drawable.pi33,
            R.drawable.pi34,
            R.drawable.pi35,
            R.drawable.pi36,
            R.drawable.pi37,
            R.drawable.pi38,
            R.drawable.pi39,
            R.drawable.pi40,
            R.drawable.pi41,
            R.drawable.pi42,
            R.drawable.pi43},43,0),

    BLUEPORTAL(new int[]{
            R.drawable.pbo01,
            R.drawable.pbo02,
            R.drawable.pbo03,
            R.drawable.pbo04,
            R.drawable.pbo05,
            R.drawable.pbo06,
            R.drawable.pbo07,
            R.drawable.pbo08,
            R.drawable.pbo09,
            R.drawable.pbo10,
            R.drawable.pbo11,
            R.drawable.pbo12,
            R.drawable.pbo13,
            R.drawable.pbo14,
            R.drawable.pbo15,
    },15,0),
    REDPORTAL(new int[]{
        R.drawable.pro01,
                R.drawable.pro02,
                R.drawable.pro03,
                R.drawable.pro04,
                R.drawable.pro05,
                R.drawable.pro06,
                R.drawable.pro07,
                R.drawable.pro08,
                R.drawable.pro09,
                R.drawable.pro10,
                R.drawable.pro11,
                R.drawable.pro12,
                R.drawable.pro13,
                R.drawable.pro14,
                R.drawable.pro15
    },15,0),


    GHOSTBLUEUP(new int[]{
            R.drawable.gbu00,
            R.drawable.gbu01,
            R.drawable.gbu02,
            R.drawable.gbu03,
            R.drawable.gbu04,
            R.drawable.gbu05,
            R.drawable.gbu06,
            R.drawable.gbu07,
            R.drawable.gbu08,
            R.drawable.gbu09,
            R.drawable.gbu10,
            R.drawable.gbu11,
            R.drawable.gbu12,
            R.drawable.gbu13
    },13,0),
    GHOSTBLUERIGHT(new int[]{
            R.drawable.gbr00,
            R.drawable.gbr01,
            R.drawable.gbr02,
            R.drawable.gbr03,
            R.drawable.gbr04,
            R.drawable.gbr05,
            R.drawable.gbr06,
            R.drawable.gbr07,
            R.drawable.gbr08,
            R.drawable.gbr09,
            R.drawable.gbr10,
            R.drawable.gbr11,
            R.drawable.gbr12,
            R.drawable.gbr13

    },13,0),
    GHOSTBLUEDOWN(new int[]{
            R.drawable.gbd00,
            R.drawable.gbd01,
            R.drawable.gbd02,
            R.drawable.gbd03,
            R.drawable.gbd04,
            R.drawable.gbd05,
            R.drawable.gbd06,
            R.drawable.gbd07,
            R.drawable.gbd08,
            R.drawable.gbd09,
            R.drawable.gbd10,
            R.drawable.gbd11,
            R.drawable.gbd12,
            R.drawable.gbd13

    },13,0),
    GHOSTBLUELEFT(new int[]{
            R.drawable.gbl00,
            R.drawable.gbl01,
            R.drawable.gbl02,
            R.drawable.gbl03,
            R.drawable.gbl04,
            R.drawable.gbl05,
            R.drawable.gbl06,
            R.drawable.gbl07,
            R.drawable.gbl08,
            R.drawable.gbl09,
            R.drawable.gbl10,
            R.drawable.gbl11,
            R.drawable.gbl12,
            R.drawable.gbl13

    },13,0),
    FIREPROJECTILE(new int[]{
            R.drawable.fp1,
            R.drawable.fp2,

    },2,0);





    public int ids[];
    public int max;
    public int terminal;

    Element(int[] ids,int max,int terminal) {
        this.ids = ids;
        this.max=max;
        this.terminal=terminal;
    }
}
